name: test
on: pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.7]
    steps:
      - name: Echo information
        run:  |
          echo ${{matrix.os}}
          echo $RUNNER_OS
          python --version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Allow running of install scripts
        run: |
          chmod +x install-gh.sh
          chmod +x test-gh.sh
      - name: Run install script
        run: bash install-gh.sh
      - name: Run test script
        run: bash test-gh.sh
