name: test
on: pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.6]
    steps:
      - name: Echo the current os
        run:  echo ${{matrix.os}}
      - name: Allow running of install scripts
        run: |
          chmod +x install.sh
          chmod +x test.sh
      - name: Run install script
        run: bash install.sh
      - name: Run test script
        run: bash test.sh
